pipeline:
    build:
      image: java:openjdk-7
      environment:
        - GRADLE_USER_HOME=~/.gradle
      commands:
        - ./gradlew test
        - curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/tranduykhanh/ci-report-tool/master/dist/framgia-ci && chmod +x /usr/bin/framgia-ci
        - framgia-ci run