pipeline:
  environment:
    - GRADLE_USER_HOME=~/.gradle
  build:
      image: java:openjdk-7
      commands:
        - curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/tranduykhanh/ci-report-tool/master/dist/framgia-ci && chmod +x /usr/bin/framgia-ci
        - ./gradlew test
        - framgia-ci run
        